source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'

link_with 'GTViewController', 'GTViewControllerTests'

pod 'TBXML', '~> 1.5', :inhibit_warnings => true
pod 'SSCWhatsAppActivity', '~> 1.0'
